AWSTemplateFormatVersion: '2010-09-09'

Description: 'CephalonAhmes ECR stack'

Resources:
  CephalonAhmesECRRepo:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: CephalonAhmesECRRepo
      ImageTagMutability: MUTABLE
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
            {
              "rulePriority": 1,
              "description": "Only keep 1 untagged image",
              "selection": {
                "tagStatus": "untagged",
                "countType": "imageCountMoreThan",
                "countNumber": 1
              },
              "action": { "type": "expire" }
            }]
          }

Outputs:
  CephalonAhmesRepositoryUri:
    Value: !GetAtt CephalonAhmesECRRepo.RepositoryUri
    Export :
      Name : CephalonAhmesRepositoryUri