version: 2

multi-ecosystem-groups:
  all-dependencies:
    schedule:
      interval: "monthly"
      cooldown:
        default-days: 30

updates:
  - package-ecosystem: "docker"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "all-dependencies"

  - package-ecosystem: "pip"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "all-dependencies"
