[PrawSettings]
PRAW_CLIENT_ID = "OverrideByEnv"
PRAW_CLIENT_SECRET = "OverrideByEnv"
PRAW_USERNAME = "OverrideByEnv"
PRAW_PASSWORD = "OverrideByEnv"
SubredditDestinationFallbacks = ["test","test2"]
NotificationDestinationUsername = "desmaraisp"
Notify = true


[S3Settings]
PostHistoryFullFileName = "testFile"
S3_BucketName = "cephalonahmesbucket"


[GeneralSettings]
footer_message = "footer"
XML_Urls=[
	"test-xml",
	"test-xml2",
]