[PrawSettings]
SubredditDestinationFallbacks = ["scrappertest"]
Notify = false


[GeneralSettings]
XML_Urls=[
	"https://forums.warframe.com/forum/3-pc-update-notes.xml",
	"https://forums.warframe.com/forum/123-developer-workshop-update-notes.xml",
	"https://forums.warframe.com/forum/170-announcements-events.xml",
	"https://forums.warframe.com/forum/36-general-discussion.xml"
]