version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "CephalonAhmesMainStack"
s3_bucket = "aws-sam-cli-changeset-bucket"
s3_prefix = "cephalonahmesstack"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"