AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cephalonAhmesStack

Parameters:
  CEPHALONAHMESPRAWUSERNAME:
    Type: String
  CEPHALONAHMESPRAWPASSWORD:
    Type: String
  CEPHALONAHMESPRAWCLIENTSECRET:
    Type: String
  CEPHALONAHMESPRAWCLIENTID:
    Type: String
  ConfigurationName:
    Type: String
    Default: ""


Resources:
  CephalonAhmesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cephalonahmesbucket


  CephalonAhmesFunction:
    Type: AWS::Serverless::Function
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ../.
      DockerBuildTarget: release
    Properties:
      PackageType: Image
      FunctionName: CephalonAhmesFunction
      Timeout: 900
      MemorySize: 256
      Environment : 
        Variables: 
          CEPHALONAHMES_PRAW_CLIENT_ID:
            Ref: CEPHALONAHMESPRAWCLIENTID
          CEPHALONAHMES_PRAW_CLIENT_SECRET: 
            Ref: CEPHALONAHMESPRAWCLIENTSECRET
          CEPHALONAHMES_PRAW_PASSWORD: 
            Ref: CEPHALONAHMESPRAWPASSWORD
          CEPHALONAHMES_PRAW_USERNAME: 
            Ref: CEPHALONAHMESPRAWUSERNAME
          ConfigurationName: 
            Ref: ConfigurationName
      Policies:
        - S3FullAccessPolicy:
            BucketName: cephalonahmesbucket

      Events:
        CephalonAhmesSchedule:
          Type: Schedule
          Properties:
            Description: Triggers AWS Lambda function every x minutes
            Enabled: true
            Name: cephalonahmesschedule
            Schedule: rate(2 minutes)

  FunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: [ CephalonAhmesFunction ]
    Properties:
      LogGroupName: !Sub /aws/lambda/${CephalonAhmesFunction}
      RetentionInDays: 7
