name: Run integration test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker-practice/actions-setup-docker@master
    - uses: aws-actions/setup-sam@v2
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Run Tests
      shell: pwsh
      run: |
        echo "Starting docker build"
        docker build . -t test --target test
        $content = @'
        PRAW_CLIENT_ID=${{ secrets.PRAW_CLIENT_ID }}
        PRAW_CLIENT_SECRET=${{ secrets.PRAW_CLIENT_SECRET }}
        PRAW_PASSWORD=${{ secrets.PRAW_PASSWORD }}
        PRAW_USERNAME=${{ secrets.PRAW_USERNAME }}
        '@
        
        $content | Set-Content -Path ./.envvars
        docker run --env-file ./.envvars --name pytest test
        echo "Tests completed"
        if($LASTEXITCODE -eq 1){
          throw "Unit tests failed"
        }
        docker cp pytest:/app/coverage.xml ./coverage.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)

    - name: Push to AWS
      if: ${{ github.event_name == 'push' }}
      shell: pwsh
      run: |
        echo "Deploying"
        aws cloudformation deploy --stack-name CephalonAhmesPipelineResources  --template-file SAMDeploy/SAMPreliminaryDeploy.yml
        
        $RepositoryUri  = aws cloudformation list-exports --query "Exports[?Name=='CephalonAhmesRepositoryUri'].Value" --no-paginate --output text

        sam build --template-file ./SAMDeploy/SAMTemplate.yaml
        sam deploy --config-file ./SAMDeploy/samconfig.toml --image-repositories "CephalonAhmesFunction=$RepositoryUri" `
          --parameter-overrides CEPHALONAHMESPRAWCLIENTID=${{ secrets.PRAW_CLIENT_ID }} CEPHALONAHMESPRAWCLIENTSECRET=${{ secrets.PRAW_CLIENT_SECRET }} CEPHALONAHMESPRAWPASSWORD=${{ secrets.PRAW_PASSWORD }} CEPHALONAHMESPRAWUSERNAME=${{ secrets.PRAW_USERNAME }} ConfigurationName=staging