name: Run integration test

on:
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nose
    - name: Set env
      run: |
        echo "CHROMEDRIVER_PATH=$(echo $CHROMEWEBDRIVER)/chromedriver" >> $GITHUB_
        echo "PRAW_CLIENT_ID=$(echo ${{ secrets.PRAW_CLIENT_ID }})" >> $GITHUB_
        echo "PRAW_CLIENT_SECRET=$(echo ${{ secrets.PRAW_CLIENT_SECRET }})" >> $GITHUB_
        echo "PRAW_PASSWORD=$(echo ${{ secrets.PRAW_PASSWORD }})" >> $GITHUB_
        echo "PRAW_USERNAME=$(echo ${{ secrets.PRAW_USERNAME }})" >> $GITHUB_
    - name: Run Tests
      run: |
        nosetests
