name: Run integration test

on:
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.8'
    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Run Tests
      env:
        PRAW_CLIENT_ID: ${{ secrets.PRAW_CLIENT_ID }}
        PRAW_CLIENT_SECRET: ${{ secrets.PRAW_CLIENT_SECRET }}
        PRAW_PASSWORD: ${{ secrets.PRAW_PASSWORD }}
        PRAW_USERNAME: ${{ secrets.PRAW_USERNAME }}
        ConfigurationName: ${{ secrets.ConfigurationName }}
        CLOUDCUBE_SECRET_ACCESS_KEY: ${{ secrets.CLOUDCUBE_SECRET_ACCESS_KEY }}
        CLOUDCUBE_ACCESS_KEY_ID: ${{ secrets.CLOUDCUBE_ACCESS_KEY_ID }}
        CLOUD_CUBE_BASE_LOC: ${{ secrets.CLOUD_CUBE_BASE_LOC }}
      run: |
        python -m pytest
