name: Run integration test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - id: GetPythonVersion
      shell: pwsh
      run: | 
        $content = Get-Content ./runtime.txt
        $version_num = [regex]::match($content, "(?<=python-)\S*").Groups[0].value
        echo "::set-output name=python_version_num::$version_num"

    - name: Set up Python
      uses: actions/setup-python@v4.0.0
      with:
        python-version: ${{ steps.GetPythonVersion.outputs.python_version_num }}
    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt
        python -m pip install -r requirements-test.txt
    - name: Run Tests
      env:
        PRAW_CLIENT_ID: ${{ secrets.PRAW_CLIENT_ID }}
        PRAW_CLIENT_SECRET: ${{ secrets.PRAW_CLIENT_SECRET }}
        PRAW_PASSWORD: ${{ secrets.PRAW_PASSWORD }}
        PRAW_USERNAME: ${{ secrets.PRAW_USERNAME }}
        ConfigurationName: ${{ secrets.ConfigurationName }}
        CLOUDCUBE_SECRET_ACCESS_KEY: ${{ secrets.CLOUDCUBE_SECRET_ACCESS_KEY }}
        CLOUDCUBE_ACCESS_KEY_ID: ${{ secrets.CLOUDCUBE_ACCESS_KEY_ID }}
        CLOUD_CUBE_BASE_LOC: ${{ secrets.CLOUD_CUBE_BASE_LOC }}
      run: python -m pytest --cov src

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
